### ISSUE TITLE
Support flash chip that only holds a single PNOR

### ISSUE THREAD

**Issue by mine260309** [openbmc/openpower-pnor-code-mgmt#1]
The current `openpower-pnor-code-mgmt` is implemented based on that the chip is able to hold two PNORs, e.g. 128MiB chip.
Most OpenPOWER systems uses 64MiB PNOR chip, and it is able to only hold a single PNOR.

This issue is to track the efforts to support such case.
Ideally, we only need to change below to support this case:
1. Enable `openpower-ubi` distro feature
2. Add `openpower-software-manager_%.bbappend` to define `ACTIVE_PNOR_MAX_ALLOWED=1` in 

However, several issues are found during testing:
1. The existing PNOR on flash is *always* functional, so during code update, it will not delete the current PNOR in `ItemUpdater::freeSpace()`, and thus the update will fail due to not enough space.
2. If we change the above code to let it delete the functional PNOR, the code update will succeed. However, the VersionID is not deleted, results in below issues:
   1. If we upload the the previous-functional PNOR again, it gets `Version already exists or failed to be extracted` error;
   2. If we managed to upload the previous-functional PNOR again, the `VersionID` is still marked as functional, so the WebUI will show both "Functional" PNORs, and the uploaded previous-functional PNOR will not show the "Activate" button. Both are wrong from WebUI perspective.

The code should handle such cases when `ACTIVE_PNOR_MAX_ALLOWED` is set to 1.

**Comment by anoo1** [comment]
Lei has implemented support for static PNOR layout which supports a single PNOR version.
